---
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Knjižara Švrća
email: knjizarasvrca@gmail.com
phone: "+38163603018"
description: Knjige, baloni, pokloni...
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
# Build settings
collections:
  baloni:
    output: 'true'
    permalink: "/:collection/:name/"
  kancelarijski_materijal:
    output: 'true'
    permalink: "/:collection/:name/"
  komision:
    output: 'true'
    permalink: "/:collection/:name/"
  nakit:
    output: 'true'
    permalink: "/:collection/:name/"
  ostalo:
    output: 'true'
    permalink: "/:collection/:name/"
  poslovne_knjige:
    output: 'true'
    permalink: "/:collection/:name/"
  rancevi_i_peratonice:
    output: 'true'
    permalink: "/:collection/:name/"
  skolski_pribor:
    output: 'true'
    permalink: "/:collection/:name/"
  sveska:
    output: 'true'
    permalink: "/:collection/:name/"
  udzbenici:
    output: 'true'
    permalink: "/:collection/:name/"
  ukrasni_papiri_i_kese:
    output: 'true'
    permalink: "/:collection/:name/"
  usluga:
    output: 'true'
    permalink: "/:collection/:name/"
theme: minima
plugins:
- jekyll-feed
